version: '3.7'
services: 
  mysql:
    image: mysql:5.7.20
#    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d:rw
      - ./mysql/conf/:/var/lib/mysql:rw
    restart: always
  mongo:
    image: mongo
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/:/data/db:rw
    restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    
    restart: always 
    volumes:
      - .:/code
