version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.1
    steps:
      - checkout
      - run: ./app.py
  test:
    docker:
      - image: circleci/mysql:mysql-server
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
