version: 2.0

jobs:
  build:
    docker:
      - image: - image: circleci/python:3.5-jessie-node-browsers-legacy
    working_directory: ~/laboratorio
    steps:
      - checkout
      # Bundle install dependencies
      - run: pip install flask
  deploy:
    machine:
        enabled: true
    working_directory: ~/laboratorio
   
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
